name: SimpleLaser
author: Flowsqy
version: ${project.version}
main: fr.flowsqy.simplelaser.SimpleLaserPlugin
api-version: "1.16"
depend:
  - Reflect
commands: 
  laser:
    description: Create a laser
    usage: /laser <startX> <startY> <startZ> <endX> <endY> <endZ> <duration> <distance>
    permission: simplelaser.command
